### ISSUE TITLE
Unable to login with steam account in panel

### ISSUE THREAD

**Issue by vedaanty** [fugasjunior/arma-server-manager#45]
Hello! We have added the steam API key in the env and are trying to login with a valid steam account in the panel with Arma 3. We have tried with and without 2FA, and with multiple accounts, yet the error persists. Without the account we are unable to setup the Arma 3 Server. We have no clue how to fix this issue. Help will be appreciated. My discord is Verdun#1924, if you want to get in touch there instead. This is running on an Ubuntu VPS through docker. Log file is attached below. 

Thanks in advance! We really need help setting this up. 

![image](https://user-images.githubusercontent.com/39668240/216754587-d6ecc882-d390-4f44-aad9-52551175f6a1.png)

LOGS:
[_armaservermanager-armaservermanager-1_logs (4).txt](https://github.com/fugasjunior/arma-server-manager/files/10608137/_armaservermanager-armaservermanager-1_logs.4.txt)

**Comment by swebow** [comment]
Hi!

I solved this by logging out from your Steam account on a webbrowser.
When you login again, it will send you an email with the Auth, copy that to the Server Manager instead.

**Comment by fugasjunior** [comment]
Hi, first of all thank you for a detailed description. As we've discussed on Discord, this issue was likely caused by an unsupported encryption key. 

The solution was to delete the encryption key from the `.env` file entirely and then recreate the container (`docker-compose down && docker-compose up -d`)`. Another solution might be to generate a new key which might work. 

I'll create a new issue to investigate and find a more reliable way to generate encryption keys.
