### ISSUE TITLE
ReadTimeoutException: Timeout occured for 'SessionId{id='SourceInfoResponse:127.0.0.1:2303'}'

### ISSUE THREAD

**Issue by swebow** [fugasjunior/arma-server-manager#49]
Hi!

Odd bug when a server is running.
The server works and all, I also see how many players and which map etc.
[_arma3-server-gui_v100-armaservermanager-1_logs.txt](https://github.com/fugasjunior/arma-server-manager/files/10612080/_arma3-server-gui_v100-armaservermanager-1_logs.txt)

Just wanted to reported if you want to take a look at it.

**Comment by fugasjunior** [comment]
This likely happens when the server has freshly started but is not fully initialized and cannot respond to status queries yet. I've added a small time window (1 minute) after the server startup during which these errors are ignored completely. I also improved the error message to be more descriptive of the problem.

Feel free to reopen this issue if you continue having problems after updating to `v1.1.0`.
