### ISSUE TITLE
Reforger config outdated

### ISSUE THREAD

**Issue by tiapfy** [fugasjunior/arma-server-manager#83]
I set up ASM in a Ubuntu VPS without Docker and when I try to install and start Arma Reforger an Unindentified Error occurs. Looking at the logs it appears to be a problem with the config file. When I start it manually with the test config file or the config file from the server instance I created it tells me that some parameters are not allowed. Looking at the wiki it seems that they updated the config parameters. If I switch the parameters and start manually it works. Is ASM going to be updated to fix this? In the meanwhile could I do something to use ASM with reforger with an updated custom config file?

**Comment by fugasjunior** [comment]
Hi, I'm aware of this bug, this has already been fixed in the `dev` branch with commit 859d7fde7c30e8985d0d4e1969a9cd94ed9266fc, but currently is not released in a stable build. If you want to, you might try a [beta release v1.1.2-beta](https://github.com/fugasjunior/arma-server-manager/releases/tag/v1.1.2-beta) which already contains a fix for this bug.

If you want to keep the stable version, you can edit and fix the config file manually. After that, you can start the server from the web UI normally. Keep in mind that the config will be regenerated from template any time the server configuration is updated from the UI.

**Comment by tiapfy** [comment]
Uh, sorry! I didn’t see the dev build

**Comment by fugasjunior** [comment]
You wouldn't, I just released it 😄 Let me know if you run across any issues, but Reforger server should work fine with this build.

**Comment by tiapfy** [comment]
Ok, I tried it and now the server appears to be installed correctly. If I try to start it through the interface though it turns off seemingly without errors. If I try to start it with the config generated by the manager with
`./ArmaReforgerServer -config ./REFORGER_3.json`
it seems to start correctly.
Here's the Reforger log:
[REFORGER_3.log](https://github.com/fugasjunior/arma-server-manager/files/13168749/REFORGER_3.log)

Here's the ASM log:
[spring-boot-logger.log](https://github.com/fugasjunior/arma-server-manager/files/13168755/spring-boot-logger.log)

**Comment by fugasjunior** [comment]
Thanks for reporting this, there was an issue with how the server launch parameters for Reforger work on Linux. You can try now, I've updated the files in the release.

**Comment by tiapfy** [comment]
Now it seems to work, thanks!
